### ISSUE TITLE
some questions about setting this up

### ISSUE THREAD

**Issue by skeddles** [ananay/passport-apple#44]
Where do i do it? I've made an apple account but cant figure out where, unless it's in the apple developers program that you have to download on an apple hardware and pay apple money, in which case it would be nice if this was made clear on the readme so people don't waste their time trying to set it up

**Comment by phuze** [comment]
You don't need apple hardware, and you don't need to pay anything.

1. Create an apple id --- https://appleid.apple.com/account
2. Login to the developer portal --- https://developer.apple.com/account/

Then read the instructions for setting up Apple Login, which are found here:
https://github.com/ananay/apple-auth/blob/master/SETUP.md

I'm going to warn you about a couple things:
1. Take your time to read documentation. Then read it again so you understand it.
2. Everything you need, will be found under "**Certificates, IDs & Profiles**" of the Apple developer site. As a tip -- if you can't find something, **pay attention to the dropdown in the upper right**.
3. Apple doesn't implement standard oAuth, because Apple. If your application requires an email, my advice is don't waste your time trying to support Apple Login -- users can simply choose not to share it and you'll end up getting back some alias which is likely meaningless to your application.
4. Just breath.

**Comment by ananay** [comment]
Sorry but your question is a little bit confusing. This doesn't exactly require Apple hardware, it's just like Sign in with Google. I believe you do have to pay for the Apple Developer Program to register your app. Please refer to the SETUP.md file for detailed steps and let me know if you still have any questions!
